export type appData = {
    university: string;
    id: number;
    fullName: string | null;
    owner: string;
    license: string | null;
    language: string | null;
    htmlUrl: string | null;
    description: string | null;
    fork: number;
    createdAt: string | null;
    updatedAt: string | null;
    pushedAt: string | null;
    homepage: string | null;
    size: number;
    stargazersCount: number;
    readme: string | null;
    watchersCount: number;
    forksCount: number;
    openIssuesCount: number;
    watchers: number;
    organization: string | null;
    releaseDownloads: number;
    contributors: string | null;
    contributorCount: number;
    busFactor: number;
    codeOfConductFile: string | null;
    contributing: string | null;
    securityPolicy: string | null;
    issueTemplates: string | null;
    pullRequestTemplate: string | null;
    subscribersCount: number;
    affiliationPredictionGpt5Mini: number;
    typePredictionGpt5Mini: string | null;
};

export type secrData = {
    htmlUrl: string;
    binaryArtifacts: number;
    branchProtection: number;
    ciTests: number;
    ciBestPractices: number;
    codeReview: number;
    contributors: number;
    dangerousWorkflow: number;
    dependencyUpdateTool: number;
    fuzzing: number;
    license: number;
    maintained: number;
    packaging: number;
    pinnedDependencies: number; 
    sast: number; 
    securityPolicy: number;
    signedReleases: number;
    tokenPermissions: number;
    vulnerabilities: number;
    totalScore: number;
};

export type orgsData = {
    login: string;
    name: string;
    description: string;
    location: string;
    company: string;
    email: string;
    url: string;
    createdAt: string;
    updatedAt: string;
    university: string;
    affiliationPredictionOrgs: string;
};
