#!/usr/bin/env bash

git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add -A
git diff --staged --quiet || git commit -m "format.yml: $(git log -1 --pretty=%B)"
git push