name: format
on: [push, pull_request]

jobs:
    format:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}

            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: 24

            - name: format frontend
              run: cd app && npm ci && npm run fmt 
            
            - name: format backend
              run: cd api && npm ci && npm run fmt 
                    
            - name: commit changes
              run: ./scripts/ci/git-bot